### ISSUE TITLE
Raspberry Pi 2 support?

### ISSUE THREAD

**Issue by luxas** [cellux/rpi-buildroot#1]
Hello!

This is a very nice project, which I am going to test.
Your manual is excellent.

I wonder however, which  `Architecture Variant` should be chosen if one is targeting the RPi 2?
Perhaps a `board/rpi-2` folder.

And is it possible to always use the latest kernel (without modifying manually)?

We are planning in Rancher OS issue rancher/os#380 to build RancherOS for the Pi.
RancherOS is using buildroot in their os-base project.

Could one merge that .config file with their's rancher.config?

I am new to these adventures, could you please give your opinion? :smile:

**Comment by cellux** [comment]
I haven't touched this project for years.

In the meantime, Buildroot advanced a lot - the 2015.05 release includes out-of-the-box support for Raspberry Pi, both v1 and v2. This project was my attempt to do something which is now included in upstream, so it's not that relevant any more. So I advise going back to Buildroot and use that.

**Comment by luxas** [comment]
Ok, didn't know that.
Using that now instead.
Thanks for your time.
